apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-service
 namespace: todoapp
 annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - http:
     paths:
     - pathType: Prefix
       path: /
       backend:
         service:
           name: todoapp-service
           port:
             number: 80
